name: pipeline
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Cache pip dependencias
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Instale Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'
      - name: Instale as dependências (cachê)
        run: pip install -r requirements.txt
      - name: Valide Conventional commits
        run: python check-commit.py
      - name: Execute os testes unitários
        run: python test_unitarios.py
      - name: Execute os testes de integração
        run: python test_integracao.py